version: 2
updates:
- package-ecosystem: gradle
  directory: "/solutions/java"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Asia/Shanghai
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.elasticsearch.client:elasticsearch-rest-high-level-client
    versions:
    - 7.11.0
- package-ecosystem: gomod
  directory: "/solutions/go/src/playground"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Asia/Shanghai
  open-pull-requests-limit: 10
