matrix:
  include:
    - language: java
      jdk: 
        - oraclejdk8
      before_script:
        - cd solutions/java
      script:
        - ./gradlew clean build
    - language: go
      go:
        - 1.10.x
      go_import_path: playground
      before_script:
        - cd solutions/go/src/playground
        - go get -u github.com/golang/dep/cmd/dep
        - $GOPATH/bin/dep ensure
      script:
        - go test -v
