matrix:
  include:
    - language: java
      jdk: openjdk11
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
      before_script:
        - cd solutions/java
      script:
        - ./gradlew clean startAllServices build stopAllServices
      after_script:
        - sh .travis.sh
      services:
        - docker
    - language: go
      go: 1.12.x
      go_import_path: playground
      install:
        - export GOPATH=${TRAVIS_BUILD_DIR}/solutions/go/
      before_script:
        - cd solutions/go/src/playground
        - go get -u github.com/golang/dep/cmd/dep
        - $GOPATH/bin/dep ensure
      script:
        - go test ./... -v
    - language: python
      python: 3.6
      before_script:
        - cd solutions/python
      script: pytest
env:
  matrix:
    secure: 6mdKBBISziS7htytQKIO+iEzblnLul5t8JIAWCiVIxen3bzl3DAVuHYiIjs604I/a2Zu3AlQRjqQcDHQ4N0mu/Kx+HAZ2adeouhT6z+XASyySiaJSH3MvQst4gPAtGpPTOOugsPV+CLPPBWQ4rvRrBehrkOIVKgQy7e6WORAddBf68i69UDBcESNyIAzHgU6FcERokdIcIWtM1rCtvSW0HWZmVHaNTVLQDv2/pLcCA0CbaxKaE6u58foGBvBRJWiPoooAHZPGiju6Sy/ZPtehu5ErFff6UMAceKG4xeKzryiONtUHe/8cw8tdbSmzAZeWjHcIdyO6VqHNmBqDq+mdmgOTturYsI4oWNt64xArMnS+yMd4dpFTAlLVB7fh+/p2QFgvHeXn5WQdrpKbVJkJF7jDWBIjuaEf2bvKL/VH5AqOXiIpbG825FkGMMuzCSbC6yVlRUfnVuG/M1QJ8w+j7B0RTE9Hk4FMu1OwWJsuGXcTVcG0FUq5QXidjDl0pzczMmOJIldrT2Pj51t7KwcDJFsZyMCScJJq4pves5WbqPeaVXqXhSQAkRitzLlGf8VHCTGjPR7ANqeUUEN5hwz6xR1lU0bMcy1it9C5JQm6cfDERC1F4eto9LZ/xY2DwQfLJqPlrefJt71EtvUrczJXaIKU5B1AahA0WLO7RbL3TU=
