schemaName: sharding_db

dataSources:
  ds_0:
    url: jdbc:mysql://mysql-master-1:3306/order_db?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
  #  ds_0_slave_0:
  #      url: jdbc:mysql://mysql-master-1-slave-1:3306/order_db?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
  #      username: root
  #      password: root
  #      connectionTimeoutMilliseconds: 30000
  #      idleTimeoutMilliseconds: 60000
  #      maxLifetimeMilliseconds: 1800000
  #      maxPoolSize: 50
  #  ds_0_slave_1:
  #    url: jdbc:mysql://mysql-master-1-slave-2:3306/order_db?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
  #    username: root
  #    password: root
  #    connectionTimeoutMilliseconds: 30000
  #    idleTimeoutMilliseconds: 60000
  #    maxLifetimeMilliseconds: 1800000
  #    maxPoolSize: 50
  ds_1:
    url: jdbc:mysql://mysql-master-2:3306/order_db?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
#  ds_1_slave_0:
#    url: jdbc:mysql://mysql-master-2-slave-1:3306/order_db?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
#    username: root
#    password: root
#    connectionTimeoutMilliseconds: 30000
#    idleTimeoutMilliseconds: 60000
#    maxLifetimeMilliseconds: 1800000
#    maxPoolSize: 50
#  ds_1_slave_1:
#    url: jdbc:mysql://mysql-master-2-slave-2:3306/order_db?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
#    username: root
#    password: root
#    connectionTimeoutMilliseconds: 30000
#    idleTimeoutMilliseconds: 60000
#    maxLifetimeMilliseconds: 1800000
#    maxPoolSize: 50
shardingRule:
  tables:
    t_order:
      actualDataNodes: ds_${0..1}.t_order_${0..1}
      databaseStrategy:
        inline:
          shardingColumn: user_id
          algorithmExpression: ds_${user_id % 2}
      tableStrategy:
        inline:
          shardingColumn: order_id
          algorithmExpression: t_order_${order_id % 2}
  bindingTables:
    - t_order
  defaultTableStrategy:
    none:
#  masterSlaveRules:
#    ds_0:
#      masterDataSourceName: ds_0
#      slaveDataSourceNames:
#        - ds_0_slave_0
#        - ds_0_slave_1
#      loadBalanceAlgorithmType: ROUND_ROBIN
#    ds_1:
#      masterDataSourceName: ds_1
#      slaveDataSourceNames:
#        - ds_1_slave_0
#        - ds_1_slave_1
#      loadBalanceAlgorithmType: ROUND_ROBIN
