version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.0
    environment:
      discovery.type: single-node
    ports:
      - "9200:9200"
      - "9300:9300"